# This file was generated by GoReleaser. DO NOT EDIT.
cask "vista" do
  version "0.1.3"

  name "vista"
  desc "Service manager with per-service and interleaved logs"
  homepage "https://github.com/kennethliu0/vista"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vista"

  on_macos do
    on_intel do
      sha256 "36c55c6e8125f3344ef582d76a1c474d486782d5a36c4f5854c117e987f79379"
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5b2bc2fdc16a1e9d1ba272f02c84a6297f34d0db5a8cc8f78ede3dea2c1c5953"
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f21258c8b90b10ef1d56f70f2f28b51860a757f03326456932509097be1e5560"
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7aba3831466f264c5b68dccc999bc74b2251f14626cfe9d6e7732fba0838481b"
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Linux_arm64.tar.gz"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vista"] if OS.mac?
  end

  # No zap stanza required
end
