# This file was generated by GoReleaser. DO NOT EDIT.
cask "vista" do
  name "vista"
  desc "Service manager with per-service and interleaved logs"
  homepage "https://github.com/kennethliu0/vista"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vista"

  on_macos do
    on_intel do
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Darwin_x86_64.tar.gz"
      sha256 "16b5d5903471636997aae0b57333c71d77255e802eab29ee10f71037793a2d78"
    end
    on_arm do
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Darwin_arm64.tar.gz"
      sha256 "1e300f618aa87ff93889a7b3515abe5a476e65b756e3079e5305a8b9deaaeaea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Linux_x86_64.tar.gz"
      sha256 "95751af318492f2ee598f14a066ac26b0cbde6cdf3e0897effe2b46111371af7"
    end
    on_arm do
      url "https://github.com/kennethliu0/vista/releases/download/v#{version}/vista_Linux_arm64.tar.gz"
      sha256 "bc4d8ee487c39bb52413f3023e6ee2da3d1bd6a5525e6b3b2c6c57dba766eeb1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vista"]
    end
  end

  # No zap stanza required
end
